### ISSUE TITLE
Focusdag 2: verder duiken in solid en ook IRMA

### ISSUE THREAD

**Issue by kad-michij** [marcvanandel/solid-quest#2]

**Comment by kad-michij** [comment]
Ideeën voor volgende focusdag:
-WebID + solid pods aanmaken voor rest team -> kijken of Inrupt het weer doet? 
-In IRMA duiken; hoe werkt dat precies, zijn er raakvlakken met Solid, zou het een rol kunnen spelen in onze oplossing?

**Comment by kad-michij** [comment]
Interessant filmpje om te bekijken rondom IRMA en Solid: [PoC Gids open standaarden](https://www.youtube.com/watch?v=svNgl1Z4Wt4&ab_channel=GIDSOpenStandaarden)

IRMA gebruiken zij als authenticatie/identificatiemiddel en vervolgens hebben ze een Solid pod daaraan gekoppeld. Dit vervangt dan de WebID? Of zit het daar weer bovenop?

Zie ook:  
-[HTI - Health Tools Interoperability](https://www.gidsopenstandaarden.org/hti-health-tools-interoperability)
-[Github GID Open Standaarden](https://github.com/GIDSOpenStandaarden)

**Comment by NickvApeldoorn** [comment]
IRMA heeft demofunctionaliteit. Zie: [(https://privacybydesign.foundation/demo/)]. De app is te downloaden in de appstore. Lijkt mij goed om dit woensdag te doen en aan de hand van een aantal demo's meer gevoel krijgen te bij IRMA. Ik ben inderdaad benieuwd of IRMA de WebID vervangt of dat dit verschillende oplossingen zijn.

**Comment by kad-michij** [comment]
Vraag; is één webid altijd gekoppeld aan één pod? Of kan je ook aan één webid, meerdere pods koppelen en zelf kiezen op welke pod je welke data opslaat?

**Comment by kad-michij** [comment]
To do: in contact komen met mensen die een solid app hebben gebouwd zodat we kennis kunnen uitwisselen

**Comment by NickvApeldoorn** [comment]
Via Inrupt (na een aantal foutmeldingen) is het gelukt om mijn WebID aan te maken: https://id.inrupt.com/nickvapeldoorn.

**Comment by kad-michij** [comment]
We proberen samen een chat aan te maken bij [Liqid Chat](https://liqid.chat/) maar Nick en Lexi komen er niet in. Ligt dit aan de site/app of aan iets anders? 🤔

**Comment by NickvApeldoorn** [comment]
Vraag: hebben wij alleen een view nodig op de pod(s) of is er een aparte pod nodig waarbinnen de koopovereenkomst wordt opgesteld?

**Comment by kad-rowla** [comment]
Als een soort van process flow voor applicatie ontwikkeling, hebben we deze plaatje gemaakt:
![zorgeloos-vastegoed-pods drawio](https://user-images.githubusercontent.com/74549995/182600244-c4470a1e-d54c-4f67-8072-1d7bde4d860e.png)

**Comment by NickvApeldoorn** [comment]
Attributen die je in IRMA kan laden om vervolgens (met toestemming) te delen:

- Woonadres (straat, huisnummer, postcode, woonplaats, gemeente) uit de BRP door de gemeente.
- Persoonsgegevens (volledige naam, voorletters, voornamen, achternaam, geslachtsnaam, geslacht, geboortedatum, leeftijd (ouder dan 12, 16, 18, 21 of 65), nationaliteit, geboorteland, BSN) uit de BRP door de gemeente.
- Persoonsgegevens van de bank (initialen, achternaam, geslacht, geboortedatum, leeftijdsgrenzen (ouder dan 12, 16, 18, 21 of 65), adres, postcode, woonplaats) van de bank via iDIN.
- E-mailadres (e-mailadres en e-mail domeinnaam) via je mail door SIDN namens stichting Privacy by Design.
- Mobiel telefoonnummer via internet of SMS door SIDN namens stichting Privacy by Design.
- Zorgverlener (AGB-code) via stichting Nuts.
- Bankrekening (IBAN, BIC-code, rekeninghouder) via iDEAL door stichting Privacy by Design.
- Onderwijs en onderzoek (voornaam, achternaam, e-mailadres, instelling, medewerker/student, lokaal registratienummer) via SURF.

**Comment by NickvApeldoorn** [comment]
Hoe om te gaan met attributen die (nog) niet in IRMA geladen kunnen worden? Deze zullen uit je Solid-pod moeten komen? Hoe werkt het überhaupt om dit soort gegevens **gevalideerd** in je Solid-pod te krijgen?

**Comment by kad-michij** [comment]
In het flow diagram moet er misschien een stap bijkomen: laden van data in je pod? Dit kan ws op verschillende manieren, bijv. via IRMA (bepaalde attributen zoals naam & adres) en manueel (invoeren koopsom). Hoe andere data toevoegen aan je pod? En hoe dit verwerken in het portaal?

**Comment by kad-michij** [comment]
Het zou mooi zijn als we een voorbeeld koopovereenkomst kunnen hergebruiken. Zie: [gedataficeerde koopovereenkomst](https://github.com/bp4mc2/bp4mc2-zvg/tree/master/informatiemodel/voorbeeld) 

Wellicht een van deze voorbeelden iets versimpelen en dit als uitgangspunt gebruiken? Er is als het goed is ook aangegeven welke data nog ingevuld moet worden en wat standaard is.

**Comment by kad-michij** [comment]
Irma heeft ook een aantal demo functionaliteiten waarmee je demo attributen kunt creëren. Dit kan nog wel eens van pas komen bij het maken van de demonstrator. Zie: https://privacybydesign.foundation/attribute-index/en/irma-demo.html

**Comment by marcvanandel** [comment]
Deze info van dag 2 is verwerkt in de README of andere issues 😉
